export const homeTabs = [
  {
    id: 332,
    tenant: 'SOA',
    moduleCode: 'module_service',
    moduleDisplayTitle: '热门服务',
    moduleWeight: 14,
    moduleIcon: '',
    moduleConfig: '{"isShowAll":1}',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '通用服务，指挥中心和礼品店',
  },
  {
    id: 425,
    tenant: 'SOA',
    moduleCode: 'module_service',
    moduleDisplayTitle: '对外介绍公司和行业',
    moduleWeight: 9,
    moduleIcon: '',
    moduleConfig: '{"isShowAll":1,"showCount":null}',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '官方介绍工具包',
  },
  {
    id: 470,
    tenant: 'soa',
    moduleCode: 'module_service',
    moduleDisplayTitle: '阳光职场',
    moduleWeight: 8,
    moduleIcon: '',
    moduleConfig: '{"isShowAll":1,"showCount":null}',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '共同打造风清气正的职场环境',
  },
  {
    id: 398,
    tenant: 'SOA',
    moduleCode: 'module_service',
    moduleDisplayTitle: '风险防范',
    moduleWeight: 8,
    moduleIcon: '',
    moduleConfig: '{"isShowAll":1}',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '提供各类风险防范服务',
  },
  {
    id: 342,
    tenant: 'SOA',
    moduleCode: 'module_service',
    moduleDisplayTitle: '提升公共战略素养',
    moduleWeight: 7,
    moduleIcon: '',
    moduleConfig: '',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '提升公共战略素养的相关课程',
  },
  {
    id: 345,
    tenant: 'SOA',
    moduleCode: 'module_service',
    moduleDisplayTitle: '公益',
    moduleWeight: 6,
    moduleIcon: '',
    moduleConfig: '',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '多种方式参与公益',
  },
  {
    id: 341,
    tenant: 'SOA',
    moduleCode: 'module_service',
    moduleDisplayTitle: '党建之窗',
    moduleWeight: 4,
    moduleIcon: '',
    moduleConfig: '{"isShowAll":1}',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '党建相关',
  },
  {
    id: 471,
    tenant: 'soa',
    moduleCode: 'module_service',
    moduleDisplayTitle: '食品安全',
    moduleWeight: 3,
    moduleIcon: '',
    moduleConfig: '{"isShowAll":1,"showCount":null}',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '食品安全各类服务',
  },
  {
    id: 475,
    tenant: 'soa',
    moduleCode: 'module_service',
    moduleDisplayTitle: '标准建设',
    moduleWeight: 1,
    moduleIcon: '',
    moduleConfig: '{"isShowAll":1,"showCount":null}',
    moduleGroup: '',
    mcModuleMenuDto: {
      id: 21,
      tenant: 'SOA',
      name: '首页',
      code: 'menu_strategy',
      weight: 10,
      status: null,
      deleted: null,
      appType: null,
    },
    moduleClassify: null,
    subModuleConfigClientDto: null,
    moduleSubTitle: '',
    comment: '标准相关服务支持',
  },
];

export const homeLastOnlineList = [
  {
    index: 1,
    title: '介绍公司基本情况',
    tags: ['内容全面', '随时报更新'],
    likeCount: 23,
    titleImg:
      'https://p0.meituan.net/smarttestvenus/5451f997aa9c1dee543572b083a8bcbe624884.png',
  },
  {
    index: 2,
    title: '介绍公司基本情况',
    tags: ['内容全面', '随时报更新'],
    likeCount: 23,
    titleImg:
      'https://p0.meituan.net/smarttestvenus/5451f997aa9c1dee543572b083a8bcbe624884.png',
  },
  {
    index: 3,
    title: '介绍公司基本情况',
    tags: ['内容全面', '随时报更新'],
    likeCount: 23,
    titleImg:
      'https://p0.meituan.net/smarttestvenus/5451f997aa9c1dee543572b083a8bcbe624884.png',
  },
  {
    index: 4,
    title: '介绍公司基本情况',
    tags: ['内容全面', '随时报更新'],
    likeCount: 23,
    titleImg:
      'https://p0.meituan.net/smarttestvenus/5451f997aa9c1dee543572b083a8bcbe624884.png',
  },
  {
    index: 5,
    title: '介绍公司基本情况',
    tags: ['内容全面', '随时报更新'],
    likeCount: 23,
    titleImg:
      'https://p0.meituan.net/smarttestvenus/5451f997aa9c1dee543572b083a8bcbe624884.png',
  },
  {
    index: 6,
    title: '介绍公司基本情况',
    tags: ['内容全面', '随时报更新'],
    likeCount: 23,
    titleImg:
      'https://p0.meituan.net/smarttestvenus/5451f997aa9c1dee543572b083a8bcbe624884.png',
  },
];

export const homeNavList = [
  {
    id: 1338,
    tenant: 'SOA',
    moduleId: 332,
    moduleCode: 'module_service',
    type: 2,
    url: '',
    title: '政府媒体数据报送',
    description: '',
    imageUrl: '',
    secImageUrl: '',
    weight: 7,
    serviceUnitClientDto: {
      id: 336,
      tenant: 'SOA',
      type: 1,
      title: '政府媒体数据报送',
      description: '闪电报告、定制报告服务',
      contentConfig: '',
    },
    encyclopediaClientDto: null,
    itemClassifyDto: {
      id: null,
      tenant: null,
      title: '其他',
      weight: -2147483648,
      description: null,
      moduleId: null,
    },
    mcNewsDto: null,
    label: [],
    remark: '闪电报告、定制报告服务',
    mcCourseDetailDto: null,
  },
  {
    id: 1615,
    tenant: 'soa',
    moduleId: 332,
    moduleCode: 'module_service',
    type: 2,
    url: '',
    title: '政府协会大屏合作',
    description: '',
    imageUrl: '',
    secImageUrl: '',
    weight: 6,
    serviceUnitClientDto: {
      id: 366,
      tenant: 'soa',
      type: 1,
      title: '政府协会大屏合作',
      description: '数据大屏开发服务',
      contentConfig: '',
    },
    encyclopediaClientDto: null,
    itemClassifyDto: {
      id: null,
      tenant: null,
      title: '其他',
      weight: -2147483648,
      description: null,
      moduleId: null,
    },
    mcNewsDto: null,
    label: [],
    remark: '数据大屏开发服务',
    mcCourseDetailDto: null,
  },
  {
    id: 1575,
    tenant: 'soa',
    moduleId: 332,
    moduleCode: 'module_service',
    type: 2,
    url: '',
    title: '国家行业协会合作',
    description: '',
    imageUrl: '',
    secImageUrl: '',
    weight: 5,
    serviceUnitClientDto: {
      id: 355,
      tenant: 'soa',
      type: 1,
      title: '国家级行业协会合作',
      description: '会议会展、商户沟通、专题活动',
      contentConfig: '',
    },
    encyclopediaClientDto: null,
    itemClassifyDto: {
      id: null,
      tenant: null,
      title: '其他',
      weight: -2147483648,
      description: null,
      moduleId: null,
    },
    mcNewsDto: null,
    label: [],
    remark: '行业权威/无预算可合作',
    mcCourseDetailDto: null,
  },
  {
    id: 1136,
    tenant: 'SOA',
    moduleId: 332,
    moduleCode: 'module_service',
    type: 2,
    url: '',
    title: '美团礼品采购',
    description: '',
    imageUrl: '',
    secImageUrl: '',
    weight: 3,
    serviceUnitClientDto: {
      id: 330,
      tenant: 'SOA',
      type: 1,
      title: '美团礼品内部大客户VIP服务',
      description: '全案服务商务礼赠、团队活动、员工关怀',
      contentConfig: '',
    },
    encyclopediaClientDto: null,
    itemClassifyDto: {
      id: null,
      tenant: null,
      title: '其他',
      weight: -2147483648,
      description: null,
      moduleId: null,
    },
    mcNewsDto: null,
    label: [],
    remark: 'VIP全案服务内部大客户',
    mcCourseDetailDto: null,
  },
  {
    id: 1651,
    tenant: 'soa',
    moduleId: 332,
    moduleCode: 'module_service',
    type: 2,
    url: '',
    title: '支持展览策划',
    description: '',
    imageUrl: '',
    secImageUrl: '',
    weight: 1,
    serviceUnitClientDto: {
      id: 389,
      tenant: 'soa',
      type: 1,
      title: '支持展览策划',
      description: '为大型展会、公关活动等场景，提供美团展区的策划服务',
      contentConfig: '',
    },
    encyclopediaClientDto: null,
    itemClassifyDto: {
      id: null,
      tenant: null,
      title: '其他',
      weight: -2147483648,
      description: null,
      moduleId: null,
    },
    mcNewsDto: null,
    label: [],
    remark: '展览策划/互动展点',
    mcCourseDetailDto: null,
  },
  {
    id: 1611,
    tenant: 'soa',
    moduleId: 332,
    moduleCode: 'module_service',
    type: 2,
    url: '',
    title: '美团吉祥物周边礼品',
    description: '',
    imageUrl: '',
    secImageUrl: '',
    weight: 1,
    serviceUnitClientDto: {
      id: 392,
      tenant: 'soa',
      type: 1,
      title: '美团新版吉祥物周边礼品',
      description: '礼品采购/开发策划服务',
      contentConfig: '',
    },
    encyclopediaClientDto: null,
    itemClassifyDto: {
      id: null,
      tenant: null,
      title: '其他',
      weight: -2147483648,
      description: null,
      moduleId: null,
    },
    mcNewsDto: null,
    label: [],
    remark: '礼品采购/开发策划服务',
    mcCourseDetailDto: null,
  },
];

export const detailData = [
  {
    title: '业务介绍',
    desc: '许多政府领导、媒体及客户，不仅关心美团本身的发展，也关心行业的发展。你可以通过《从数字生活到数字社会——中国数字经济年度观察》一书，对外介绍生活服务行业的发展，以及美团在行业内的实践。',
    id: 'detail-anchor-1',
  },
  {
    title: '本书使用场景',
    desc: '许多政府领导、媒体及客户，不仅关心美团本身的发展，也关心行业的发展。你可以通过《从数字生活到数字社会——中国数字经济年度观察》一书，对外介绍生活服务行业的发展，以及美团在行业内的实践。',
    id: 'detail-anchor-2',
  },
  {
    title: '如何获取本书',
    desc: '许多政府领导、媒体及客户，不仅关心美团本身的发展，也关心行业的发展。你可以通过《从数字生活到数字社会——中国数字经济年度观察》一书，对外介绍生活服务行业的发展，以及美团在行业内的实践。',
    id: 'detail-anchor-3',
  },
  {
    title: '服务团队',
    desc: '许多政府领导、媒体及客户，不仅关心美团本身的发展，也关心行业的发展。你可以通过《从数字生活到数字社会——中国数字经济年度观察》一书，对外介绍生活服务行业的发展，以及美团在行业内的实践。',
    id: 'detail-anchor-4',
  },
  {
    title: '常见问题',
    desc: '许多政府领导、媒体及客户，不仅关心美团本身的发展，也关心行业的发展。你可以通过《从数字生活到数字社会——中国数字经济年度观察》一书，对外介绍生活服务行业的发展，以及美团在行业内的实践。',
    id: 'detail-anchor-5',
  },
  {
    title: '评价',
    desc: '许多政府领导、媒体及客户，不仅关心美团本身的发展，也关心行业的发展。你可以通过《从数字生活到数字社会——中国数字经济年度观察》一书，对外介绍生活服务行业的发展，以及美团在行业内的实践。',
    id: 'detail-anchor-6',
  },
];

export const detailContent = {
  title: '政府媒体数据报送',
  headInfo: [
    {
      type: null,
      name: '',
      videoId: null,
      url: 'http://p1.meituan.net/portalweb/c958a9c933b27ee7517be6b4f33ddbf91423098.jpg',
      videoPicture:
        'http://p0.meituan.net/portalweb/5daf2007023e0d8dea6ec2071ece61e7284637.jpg',
      videoPictureName: null,
      newVideoId: null,
    },
    {
      type: 1,
      name: '',
      videoId: '387702307630970913',
      url: null,
      videoPicture:
        'http://p0.meituan.net/portalweb/5daf2007023e0d8dea6ec2071ece61e7284637.jpg',
      videoPictureName: null,
      newVideoId: null,
    },
  ],
  description: '闪电报告、定制报告服务',
  bizIntroduction:
    '季末年初、消费旺季结束的时候，政府部门、主流媒体通常都需要一些消费市场大数据，你可以通过“闪电报告”自助一键获取，快速报送对方。如果有定制化需求，我们也可以快速响应，提供咨询和支持服务。',
  accumulated: null,
  label: ['自助获取', '支持定制', '多主题', '各地域'],
  type: 1,
  cooperationAdvantage: {
    id: null,
    title: '闪电报告',
    type: null,
    num: null,
    urls: null,
    content:
      '<p><b>报告种类</b></p><p>- 《数字消费报告》，可查看某区域美团各业务发展全平台消费情况，下载量400+</p><p>- 《节假日预测报告》，元旦、春节、清明、五一、十一等客流、消费预测，下载量600+</p><p>- 《文旅报告》，涵盖“吃住行游购娱”六大文旅场景，下载量400+</p><p>- 《夜间经济报告》，聚焦夜间经济分析促进城市消费，下载量100+</p><p>可关注订阅学城👉<a href="https://km.sankuai.com/page/877174349" target="_blank" style="background-color: rgb(255, 255, 255);"><font color="#4d80bf">报告示例</font></a>👈</p><p><br/></p><p><b>使用方式</b><br/></p><p>1. 联系谢伟（xiewei22）开通服务，通过常驻入口「手机大象-工作台-闪闪-闪电报告」或「工作台-闪电报告」进入，填写申请，选择类型，说明背景</p><p>2. 上级、系统管理员依次审批通过后，通常15分钟内大象推送报告，如遇高峰期或大型报告24小时内生成</p>',
  },
  cooperationCase: {
    id: null,
    title: '',
    cases: [],
  },
  cooperationCondition: {
    id: null,
    title: '定制报告',
    type: null,
    num: null,
    urls: null,
    content:
      '<p><b>报告领域</b><br/></p><p>数字消费、节假日消费、文旅、夜间经济、地方菜系、老字号、商圈等</p><p><br/></p><p><b>使用方式</b><br/></p><p>1. 提交初步需求 👉<a href="https://tt.sankuai.com/ticket/custom/create/165/524" target="_blank"><font color="#4d80bf">TT工单提交</font><span></span></a>👈</p><p>2. 上级、CAP数据团队负责人、CAP研发中心负责人对需求进行判断和审批</p><p>3. 数据团队对定制报告提供咨询建议，确认需求后约2周可交付，特殊情况可以再沟通</p>',
  },
  cooperationProcess: {
    id: null,
    title: '服务团队',
    type: null,
    num: null,
    urls: null,
    content:
      '<p><b>服务1号位</b></p><p>闪电报告：谢伟（xiewei22）</p><p>定制报告：王文龙（wangewnlong04）</p><p><br/></p><p><b>服务联系人<br/></b></p><p>闪电报告：谢伟（xiewei22）</p><p>定制报告：王琪（wangqi113）</p>',
  },
  questions: {
    id: null,
    title: '常见问题',
    type: null,
    num: null,
    urls: null,
    content:
      '<p><b>1. 报告收费吗？</b></p><p>无收费要求。特殊情况，可对外报价用于价值体现，相关流程请咨询自己的财务BP。</p><p><b><br/></b></p><p><b>2. 报告如何解读，或者定制报告如何提需求，能提供一些培训么？</b></p><p>1）闪电报告基于常见需求生产，维度和用语通俗，每份报告有简介，申请页面及学城可查阅<font size="3">👉<a href="https://km.sankuai.com/page/877174349" target="_blank"><font color="#4d80bf">报告介绍</font><span></span></a>👈，因此无固定培训，如有诉求可按需组织；</font></p><p><font size="3">2）定制报告由于成本较高，需要单独提交工单进行充分沟通评估，</font><span style="font-size: 14px;">&nbsp;</span><font size="3">👉<a href="https://tt.sankuai.com/ticket/custom/create/165/524" target="_blank" style="background-color: rgb(255, 255, 255);"><font color="#4d80bf">TT工单提交</font></a>👈；</font></p>',
  },
  usefulCount: 12,
  isUseful: null,
  customerServiceType: 2,
  customerServiceInfo: '',
  applicationLink: {
    type: null,
    appLink: null,
    id: null,
    path: null,
    link: null,
    btnText: null,
    enableRegForm: false,
    formKey: '',
    linkConfig: {
      type: 0,
      appLink: 'https://mtv.sankuai.com/platform/unifyData/homePage',
      id: '',
      path: '',
      link: '',
      btnText: '获取闪电报告',
      needSource: false,
      downloadType: false,
      downloadLink: '',
      appId: '',
    },
    regLinkConfig: {
      needJumpOnFormSubmit: false,
      enableOptionJumpLink: false,
      linkConfig: {
        type: 0,
        appLink: '',
        id: '',
        path: '',
        link: '',
        btnText: '',
        needSource: false,
        downloadType: false,
        downloadLink: '',
        appId: '',
      },
      fieldKey: '',
      optionLinks: [],
    },
    extLinkConfig: {
      type: 0,
      appLink: 'https://tt.sankuai.com/ticket/custom/create/165/524',
      id: '',
      path: '',
      link: '',
      btnText: '获取定制报告',
      needSource: false,
      downloadType: false,
      downloadLink: '',
      appId: '',
    },
  },
  feedbackLink: 'https://km.sankuai.com/space/CAPSOA',
  mcNewsDtoList: [],
  pageTitle: '',
  mcCourseDtoList: null,
  productType: '商家入驻',
  servicePv: 2251,
  mcServiceApplyDataDto: {
    applyBtnPv: null,
    avatarUrlList: null,
  },
};

export const commentList = [
  {
    avatar:
      'https://p0.meituan.net/smarttestvenus/5d52f8079871447d464f82c75e0cc1dc44568.jpg',
    name: '张伟/zhangwei',
    creatTime: '12-02 06:10',
    commentId: '123',
    isMyComment: false,
    content:
      '很多外部合作伙伴都很关注数字经济话题。这本书用详实的案例和数据，介绍了生活服务业数字化发展的情况，也介绍了美团的实践。我们在拜访高校老师、学会时会赠送这本书，客户反馈很不错。有简装本和礼盒版，可以轻松适配各类对外交流场合～',
  },
  {
    avatar:
      'https://p0.meituan.net/smarttestvenus/5d52f8079871447d464f82c75e0cc1dc44568.jpg',
    name: '张伟/zhangwei',
    creatTime: '12-02 06:10',
    commentId: '123',
    isMyComment: false,
    content:
      '很多外部合作伙伴都很关注数字经济话题。这本书用详实的案例和数据，介绍了生活服务业数字化发展的情况，也介绍了美团的实践。我们在拜访高校老师、学会时会赠送这本书，客户反馈很不错。有简装本和礼盒版，可以轻松适配各类对外交流场合～',
  },
  {
    avatar:
      'https://p0.meituan.net/smarttestvenus/5d52f8079871447d464f82c75e0cc1dc44568.jpg',
    name: '张伟/zhangwei',
    creatTime: '12-02 06:10',
    commentId: '123',
    isMyComment: false,
    content:
      '很多外部合作伙伴都很关注数字经济话题。这本书用详实的案例和数据，介绍了生活服务业数字化发展的情况，也介绍了美团的实践。我们在拜访高校老师、学会时会赠送这本书，客户反馈很不错。有简装本和礼盒版，可以轻松适配各类对外交流场合～',
  },
];
